name: Chained Jobs Workflow

on:
  push:        # triggers on any branch
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "hello from job1"

  job2:
    runs-on: ubuntu-latest
    needs: job1      # Chained job â€“ runs only after job1
    steps:
      - name: Print Message After Job1
        run: echo "hello from job2 - job1 completed"
